In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
df = pd.read_csv("Groceries.csv", sep=",", index_col='index', converters={'items': ast.literal_eval})
df = df["items"]
df

index
0        [sausage, whole milk, semi-finished bread, yog...
1                        [whole milk, pastry, salty snack]
2                           [canned beer, misc. beverages]
3                              [sausage, hygiene articles]
4                               [soda, pickled vegetables]
                               ...
14958    [tropical fruit, berries, other vegetables, yo...
14959                               [bottled water, herbs]
14960                      [fruit/vegetable juice, onions]
14961         [soda, root vegetables, semi-finished bread]
14962                     [bottled beer, other vegetables]
Name: items, Length: 14963, dtype: object

In [6]:
encoder = TransactionEncoder()
transactions = encoder.fit(df).transform(df)
df = pd.DataFrame(transactions, columns=encoder.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14958,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,True,False
14959,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14960,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14961,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14962,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.dtypes

Instant food products    bool
UHT-milk                 bool
abrasive cleaner         bool
artif. sweetener         bool
baby cosmetics           bool
                         ...
white bread              bool
white wine               bool
whole milk               bool
yogurt                   bool
zwieback                 bool
Length: 167, dtype: object

In [15]:
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.1)
sorted_rules = rules.sort_values('lift', ascending=False)
sorted_rules[["antecedents", "consequents", "lift"]]

          antecedents   consequents      lift
3            (yogurt)  (whole milk)  0.822940
1        (rolls/buns)  (whole milk)  0.804028
0  (other vegetables)  (whole milk)  0.769430
2              (soda)  (whole milk)  0.758296

In [16]:
frequent_itemsets

     support                        itemsets
0   0.021386                      (UHT-milk)
1   0.033950                          (beef)
2   0.021787                       (berries)
3   0.016574                     (beverages)
4   0.045312                  (bottled beer)
..       ...                             ...
64  0.010559  (rolls/buns, other vegetables)
65  0.014837  (whole milk, other vegetables)
66  0.013968        (rolls/buns, whole milk)
67  0.011629              (whole milk, soda)
68  0.011161            (whole milk, yogurt)

[69 rows x 2 columns]